import { createServer } from 'node:http';
import { randomBytes, randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { WebSocketServer, WebSocket } from 'ws';
import { createGame, pickupPile, projectForPlayer, resolveFaceDownAttempt, resolvePlay } from './lib/game-server.mjs';

const rooms = new Map(); const code = () => `MORT-${randomBytes(3).toString('base64url').toUpperCase().slice(0, 4)}`; const token = () => randomBytes(32).toString('base64url'); const roomFor = (value) => rooms.get((value || '').toUpperCase());
const files = { '/': [new URL('./public/index.html', import.meta.url), 'text/html; charset=utf-8'], '/client.js': [new URL('./public/client.js', import.meta.url), 'text/javascript; charset=utf-8'], '/styles.css': [new URL('./app/globals.css', import.meta.url), 'text/css; charset=utf-8'] };
const httpServer = createServer(async (req, res) => { const path = new URL(req.url || '/', 'http://localhost').pathname; if (!files[path]) return res.writeHead(404).end('Not found'); try { let body = await readFile(files[path][0], 'utf8'); if (path === '/styles.css') body = body.replace("@import 'tailwindcss';", ''); res.writeHead(200, { 'content-type': files[path][1], 'cache-control': 'no-store' }).end(body); } catch { res.writeHead(500).end('Could not load app'); } });
const wss = new WebSocketServer({ noServer: true }); httpServer.on('upgrade', (request, socket, head) => { if (new URL(request.url || '/', 'http://localhost').pathname !== '/ws') return socket.destroy(); wss.handleUpgrade(request, socket, head, (ws) => wss.emit('connection', ws)); });
const send = (socket, event, data) => { if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ event, data })); }; const error = (socket, message) => send(socket, 'error', { message });
function attach(socket, room, player) { player.sockets.add(socket); socket.roomCode = room.code; socket.playerId = player.id; }
function emitState(room) { for (const player of room.players) for (const socket of player.sockets) { if (!room.game) send(socket, 'room:waiting', { roomCode: room.code, inviteUrl: `${room.origin}/?room=${room.code}` }); else send(socket, 'game:state', { game: projectForPlayer(room.game, player.id), roomCode: room.code, connected: room.players.map((p) => ({ id: p.id, connected: [...p.sockets].some((s) => s.readyState === WebSocket.OPEN) })) }); } }
function createRoom(socket, payload) { let roomCode; do roomCode = code(); while (rooms.has(roomCode)); const player = { id: randomUUID(), token: token(), sockets: new Set() }; const origin = payload.origin || `http://localhost:${process.env.PORT || 3000}`; const room = { code: roomCode, players: [player], game: null, origin, updatedAt: Date.now(), rematchVotes: new Set() }; rooms.set(roomCode, room); attach(socket, room, player); send(socket, 'room:created', { roomCode, playerToken: player.token, inviteUrl: `${origin}/?room=${roomCode}` }); emitState(room); }
function joinRoom(socket, payload) { const room = roomFor(payload.roomCode); if (!room) return error(socket, 'ROOM_NOT_FOUND'); let player = room.players.find((p) => p.token === payload.playerToken); if (!player) { if (room.players.length >= 2) return error(socket, 'ROOM_FULL'); player = { id: randomUUID(), token: token(), sockets: new Set() }; room.players.push(player); } attach(socket, room, player); room.updatedAt = Date.now(); if (room.players.length === 2 && !room.game) room.game = createGame(room.code, [room.players[0].id, room.players[1].id]); send(socket, 'room:joined', { roomCode: room.code, playerToken: player.token, inviteUrl: `${room.origin}/?room=${room.code}` }); emitState(room); }
function resolveAction(socket, payload, resolver) { const room = roomFor(socket.roomCode); const player = room?.players.find((p) => p.id === socket.playerId); if (!room || !player || !room.game) return error(socket, 'NOT_IN_GAME'); try { room.game = resolver(room.game, player.id, payload); room.updatedAt = Date.now(); emitState(room); } catch (cause) { error(socket, cause instanceof Error ? cause.message : 'INVALID_ACTION'); } }
wss.on('connection', (socket) => { socket.on('message', (raw) => { try { const { event, payload = {} } = JSON.parse(raw.toString()); if (event === 'room:create') return createRoom(socket, payload); if (event === 'room:join') return joinRoom(socket, payload); if (event === 'game:play') return resolveAction(socket, payload, (game, id, data) => resolvePlay(game, id, data.cardIds || [], data.version)); if (event === 'game:faceDown') return resolveAction(socket, payload, (game, id, data) => resolveFaceDownAttempt(game, id, data.cardId, data.version)); if (event === 'game:pickup') return resolveAction(socket, payload, (game, id, data) => pickupPile(game, id, data.version)); if (event === 'game:rematch') { const room = roomFor(socket.roomCode); if (!room?.game) return error(socket, 'NOT_IN_GAME'); room.rematchVotes.add(socket.playerId); if (room.rematchVotes.size === 2) { room.game = createGame(room.code, [room.players[0].id, room.players[1].id]); room.rematchVotes.clear(); emitState(room); } return; } error(socket, 'UNKNOWN_EVENT'); } catch { error(socket, 'BAD_MESSAGE'); } }); socket.on('close', () => { const room = roomFor(socket.roomCode); const player = room?.players.find((p) => p.id === socket.playerId); if (room && player) { player.sockets.delete(socket); room.updatedAt = Date.now(); emitState(room); } }); });
setInterval(() => { const now = Date.now(); for (const [key, room] of rooms) if (!room.players.some((p) => p.sockets.size) && now - room.updatedAt > 3 * 60 * 60 * 1000) rooms.delete(key); }, 600000).unref();
httpServer.listen(Number(process.env.PORT || 3000), '0.0.0.0', () => console.log(`Mortadello listening on ${process.env.PORT || 3000}`));
