'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { io, type Socket } from 'socket.io-client';

type CardData = { id: string; rank: string; suit: string };
type GameView = { id: string; version: number; activePlayer: string; winner?: string; message: string; drawCount: number; discard: CardData[]; player: { id: string; hand: CardData[]; faceUp: CardData[]; faceDown: CardData[] }; opponent: { id: string; handCount: number; faceUp: CardData[]; faceDownCount: number } };
const symbols: Record<string, string> = { clubs: '♣', diamonds: '♦', hearts: '♥', spades: '♠' };
const red = (suit: string) => suit === 'diamonds' || suit === 'hearts';
const label = (card: CardData) => `${card.rank} of ${card.suit[0].toUpperCase()}${card.suit.slice(1)}`;

function Card({ card, back = false, selected = false, onClick, compact = false, disabled = false }: { card?: CardData; back?: boolean; selected?: boolean; onClick?: () => void; compact?: boolean; disabled?: boolean }) {
  const cls = `card ${back ? 'card--back' : ''} ${selected ? 'card--selected' : ''} ${compact ? 'card--compact' : ''}`;
  if (back) return <button className={cls} aria-label="Face-down card" onClick={onClick} disabled={disabled}><span className="card__star">★</span></button>;
  if (!card) return <div className="card card--empty" />;
  const suit = symbols[card.suit]; return <button className={cls} onClick={onClick} disabled={disabled} aria-label={`${selected ? 'Selected: ' : ''}${label(card)}`}><span className={`card__corner ${red(card.suit) ? 'red' : ''}`}><b>{card.rank}</b><small>{suit}</small></span><span className={`card__suit ${red(card.suit) ? 'red' : ''}`}>{suit}</span><span className={`card__corner card__corner--bottom ${red(card.suit) ? 'red' : ''}`}><b>{card.rank}</b><small>{suit}</small></span></button>;
}
function Stack({ card, onClick, hiddenTop = false }: { card?: CardData; onClick?: () => void; hiddenTop?: boolean }) { return <div className="stack"><Card back /><Card card={card} back={hiddenTop} onClick={onClick}/></div>; }
function IconButton({ icon, label: ariaLabel, onClick }: { icon: string; label: string; onClick?: () => void }) { return <button className="icon-button" aria-label={ariaLabel} onClick={onClick}>{icon}</button>; }

function Rules({ close }: { close: () => void }) { return <div className="modal-wrap" role="dialog" aria-modal="true"><div className="modal"><button className="modal__close" onClick={close} aria-label="Close rules">×</button><p className="eyebrow">HOW TO PLAY</p><h2>Mortadello rules</h2><div className="rules-copy"><p>Clear your hand, then face-up cards, then face-down cards. Normal ranks go 4 through King; play a higher or equal rank.</p><p><b>2</b> resets. <b>3</b> is transparent. <b>10</b> burns the pile and you play again. <b>A</b> demands a special card. Four matching ranks clears the pile.</p><p>While the draw pile has cards, every successful hand play refills your hand to three cards. If you cannot play, pick up the discard pile.</p></div></div></div>; }

function Lobby({ create, join, roomCode, setRoomCode, invite, waiting, error }: { create: () => void; join: () => void; roomCode: string; setRoomCode: (value: string) => void; invite: string; waiting: boolean; error: string }) {
  const [mode, setMode] = useState<'home'|'create'|'join'>(invite ? 'create' : 'home');
  return <main className="lobby"><div className="lobby__card"><div className="brand-mark">M</div><p className="eyebrow">A TWO-PLAYER CARD GAME</p><h1>MORTADELLO</h1><p className="lobby__intro">A graceful game of nerve, timing and the cards you dare to turn over.</p>
    {mode === 'home' && <div className="lobby__actions"><button className="primary" onClick={() => { setMode('create'); create(); }}>Create game</button><button className="secondary" onClick={() => setMode('join')}>Join game</button></div>}
    {mode === 'create' && <div className="room-panel"><span className="room-panel__label">YOUR ROOM CODE</span><strong>{roomCode}</strong><p>{waiting ? 'Share the invite. Your opponent can join from any device.' : 'Preparing your room…'}</p>{invite && <><button className="primary" onClick={() => navigator.clipboard?.writeText(invite)}>Copy invite link</button><code className="invite-url">{invite}</code></>}<button className="text-button" onClick={() => setMode('home')}>Back</button></div>}
    {mode === 'join' && <div className="room-panel"><label htmlFor="room-code">ROOM CODE</label><input id="room-code" placeholder="MORT-7K4P" value={roomCode} onChange={(e) => setRoomCode(e.target.value.toUpperCase())}/><button className="primary" disabled={!roomCode} onClick={join}>Join game</button><button className="text-button" onClick={() => setMode('home')}>Back</button></div>}
    {error && <p className="form-error">{error}</p>}
  </div></main>;
}

export default function Home() {
  const socket = useRef<Socket | null>(null); const [game, setGame] = useState<GameView | null>(null); const [roomCode, setRoomCode] = useState(''); const [invite, setInvite] = useState(''); const [waiting, setWaiting] = useState(false); const [connected, setConnected] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [showRules, setShowRules] = useState(false); const [showChat, setShowChat] = useState(false); const [settings, setSettings] = useState(false); const [menu, setMenu] = useState(false);
  useEffect(() => { const client = io({ transports: ['websocket', 'polling'] }); socket.current = client; const query = new URLSearchParams(window.location.search); const code = query.get('room'); if (code) setRoomCode(code.toUpperCase()); client.on('room:waiting', ({ roomCode: code, inviteUrl }) => { setRoomCode(code); setInvite(inviteUrl); setWaiting(true); }); client.on('game:state', ({ game: next, roomCode: code, connected: presence }) => { setGame(next); setRoomCode(code); setWaiting(false); setConnected(presence.some((p: { id: string; connected: boolean }) => p.id !== next.player.id && p.connected)); setError(''); }); client.on('connect_error', () => setError('Connection lost. Reconnecting…')); if (code) setTimeout(() => joinRoom(code), 0); return () => client.close(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  function persist(code: string, playerToken: string) { localStorage.setItem(`mortadello:${code}`, playerToken); setRoomCode(code); setInvite(`${window.location.origin}/?room=${code}`); }
  function createRoom() { setError(''); socket.current?.emit('room:create', { origin: window.location.origin }, (result: { ok: boolean; roomCode?: string; playerToken?: string; inviteUrl?: string; error?: string }) => { if (!result.ok || !result.roomCode || !result.playerToken) return setError(result.error || 'Could not create room.'); persist(result.roomCode, result.playerToken); setInvite(result.inviteUrl || ''); setWaiting(true); }); }
  function joinRoom(code = roomCode) { const normalized = code.trim().toUpperCase(); if (!normalized) return; setError(''); socket.current?.emit('room:join', { roomCode: normalized, playerToken: localStorage.getItem(`mortadello:${normalized}`) }, (result: { ok: boolean; roomCode?: string; playerToken?: string; inviteUrl?: string; error?: string }) => { if (!result.ok || !result.roomCode || !result.playerToken) return setError(result.error === 'ROOM_FULL' ? 'That room already has two players.' : 'Room not found. Check the invite or code.'); persist(result.roomCode, result.playerToken); }); }
  const hand = game?.player.hand || []; const selectedCards = hand.filter((card) => selected.includes(card.id)); const myTurn = Boolean(game && game.activePlayer === game.player.id && !game.winner); const canPlay = myTurn && selectedCards.length > 0 && selectedCards.every((card) => card.rank === selectedCards[0].rank);
  function select(card: CardData) { if (!myTurn) return; setSelected((current) => current.includes(card.id) ? current.filter((id) => id !== card.id) : current.length && hand.find((item) => item.id === current[0])?.rank !== card.rank ? [card.id] : [...current, card.id]); }
  function action(event: 'game:play'|'game:pickup'|'game:faceDown', payload: object) { if (!game) return; socket.current?.emit(event, { ...payload, version: game.version }, (result: { ok: boolean; error?: string }) => { if (!result.ok) setError(result.error === 'ILLEGAL_PLAY' ? 'That play is not legal.' : result.error || 'Move rejected.'); }); }
  function play() { if (canPlay) { action('game:play', { cardIds: selected }); setSelected([]); } }
  if (!game) return <Lobby create={createRoom} join={() => joinRoom()} roomCode={roomCode} setRoomCode={setRoomCode} invite={invite} waiting={waiting} error={error} />;
  const opponentCards = Math.min(game.opponent.handCount, 5); const playerTable = game.player.faceUp.length ? game.player.faceUp.map((card) => <Stack card={card} key={card.id}/>) : Array.from({ length: game.player.faceDown.length }, (_, index) => <Stack hiddenTop onClick={() => myTurn && action('game:faceDown', { cardId: game.player.faceDown[index].id })} key={game.player.faceDown[index].id}/>);
  const discard = game.discard[game.discard.length - 1];
  return <main className="game-shell"><div className="board"><header className="game-topbar"><div className="topbar-left"><IconButton icon="☰" label="Open menu" onClick={() => setMenu(!menu)} />{menu && <div className="popover menu-popover"><button onClick={() => setShowRules(true)}>Game rules</button><button onClick={() => window.location.assign('/')}>Return to lobby</button></div>}</div><span className="turn-pill">{myTurn ? 'Your turn' : 'Opponent'}</span><div className="topbar-actions"><IconButton icon="⚙" label="Settings" onClick={() => setSettings(!settings)} /><IconButton icon="◯" label="Open chat" onClick={() => setShowChat(true)} />{settings && <div className="popover settings-popover"><label><input type="checkbox" defaultChecked /> Sound effects</label><label><input type="checkbox" defaultChecked /> Motion</label></div>}</div></header>
    <section className="opponent-hand hand-panel"><h2>Opponent’s Hand <span>{game.opponent.handCount} cards</span></h2><div className="opponent-cards">{Array.from({ length: opponentCards }, (_, index) => <Card back compact key={index}/>)}</div></section>
    <section className="opponent-table table-row" aria-label="Opponent table cards">{game.opponent.faceUp.map((card) => <Stack card={card} key={card.id}/>)}</section>
    <section className="piles"><div className="pile"><div className="pile-stack"><Card card={discard}/><i/><i/></div><span>Discard Pile</span></div><div className="pile"><div className="pile-stack"><Card back/><i/><i/></div><span>Draw Pile <b>{game.drawCount}</b></span></div></section>
    <section className="player-table table-row" aria-label="Your table cards">{playerTable}</section><span className="you-pill">You</span>
    <section className="your-hand hand-panel"><h2>Your Hand <span>{hand.length} cards</span></h2><div className="hand-scroll">{hand.map((card) => <Card card={card} key={card.id} selected={selected.includes(card.id)} onClick={() => select(card)} disabled={!myTurn}/>)}</div></section>
    <aside className="status-message" aria-live="polite">{error || (!connected ? 'Opponent reconnecting…' : game.message)}</aside><div className="game-actions"><button className="pickup" disabled={!myTurn} onClick={() => action('game:pickup', {})}>Pick up</button><button className="end-turn" disabled={!canPlay} onClick={play}>{canPlay ? 'Play selected' : myTurn ? 'Select a card' : 'Opponent’s turn'}</button></div>
    {showChat && <div className="chat-panel"><div><b>Table chat</b><button onClick={() => setShowChat(false)} aria-label="Close chat">×</button></div><p>Chat is coming next. Focus on the duel.</p></div>}
    {game.winner && <div className="modal-wrap"><div className="modal victory"><p className="eyebrow">MORTADELLO</p><h2>{game.winner === game.player.id ? 'You Win!' : 'You Lost'}</h2><button className="primary" onClick={() => socket.current?.emit('game:rematch', {})}>Play again</button><button className="text-button" onClick={() => window.location.assign('/')}>Return to lobby</button></div></div>}
  </div>{showRules && <Rules close={() => setShowRules(false)} />}</main>;
}
