const ranks = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'];
const normalRanks = ['4', '5', '6', '7', '8', '9', 'J', 'Q', 'K'];
const specials = new Set(['2', '3', '10', 'A']);
export const makeDeck = () => ['clubs', 'diamonds', 'hearts', 'spades'].flatMap((suit) => ranks.map((rank) => ({ id: `${rank}-${suit}`, rank, suit })));
export const shuffle = (cards) => { const out = [...cards]; for (let i = out.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [out[i], out[j]] = [out[j], out[i]]; } return out; };
export function createGame(id, playerIds) { const deck = shuffle(makeDeck()); const take = () => deck.pop(); const player = (pid) => ({ id: pid, hand: [take(), take(), take()], faceUp: [take(), take(), take()], faceDown: [take(), take(), take()] }); return { id, version: 1, players: [player(playerIds[0]), player(playerIds[1])], drawPile: deck, discard: [], activePlayer: playerIds[0], message: 'Game started' }; }
export function getActivePileState(discard) { for (let i = discard.length - 1; i >= 0; i--) { const rank = discard[i].rank; if (rank === '3') continue; if (rank === '2') return { reset: true, requiresSpecial: false }; return { effectiveRank: rank, reset: false, requiresSpecial: rank === 'A' }; } return { reset: false, requiresSpecial: false }; }
export function canPlayCards(discard, cards) { if (!cards.length || cards.some((c) => c.rank !== cards[0].rank)) return false; const rank = cards[0].rank; const active = getActivePileState(discard); if (active.requiresSpecial) return specials.has(rank); if (specials.has(rank) || !active.effectiveRank || active.reset) return true; return normalRanks.indexOf(rank) >= normalRanks.indexOf(active.effectiveRank); }
const clone = (state) => ({ ...state, players: state.players.map((p) => ({ ...p, hand: [...p.hand], faceUp: [...p.faceUp], faceDown: [...p.faceDown] })), drawPile: [...state.drawPile], discard: [...state.discard] });
const playerFor = (state, id) => state.players.find((p) => p.id === id);
const other = (state, id) => state.players.find((p) => p.id !== id);
const cardsForTurn = (p, drawEmpty) => p.hand.length ? { source: 'hand', cards: p.hand } : !drawEmpty ? { source: 'hand', cards: [] } : p.faceUp.length ? { source: 'faceUp', cards: p.faceUp } : { source: 'faceDown', cards: p.faceDown };
const replenish = (state, p) => { while (p.hand.length < 3 && state.drawPile.length) p.hand.push(state.drawPile.pop()); };
const sequenceCount = (discard, rank) => { let count = 0; for (let i = discard.length - 1; i >= 0; i--) { if (discard[i].rank === '3') continue; if (discard[i].rank !== rank) break; count++; } return count; };
const checkWinner = (state, p) => { if (!p.hand.length && !p.faceUp.length && !p.faceDown.length) { state.winner = p.id; state.message = `${p.id} wins!`; } };
export function resolvePlay(current, playerId, cardIds, expectedVersion) { if (current.version !== expectedVersion) throw new Error('STALE_ACTION'); if (current.winner) throw new Error('GAME_OVER'); if (current.activePlayer !== playerId) throw new Error('NOT_YOUR_TURN'); const state = clone(current); const player = playerFor(state, playerId); const turn = cardsForTurn(player, !state.drawPile.length); if (turn.source === 'faceDown') throw new Error('USE_FACE_DOWN_ACTION'); const played = turn.cards.filter((card) => cardIds.includes(card.id)); if (played.length !== cardIds.length || !canPlayCards(state.discard, played)) throw new Error('ILLEGAL_PLAY'); player[turn.source] = player[turn.source].filter((card) => !cardIds.includes(card.id)); state.discard.push(...played); if (turn.source === 'hand') replenish(state, player); const rank = played[0].rank; const cleared = rank === '10' || sequenceCount(state.discard, rank) >= 4; if (cleared) { state.discard = []; state.activePlayer = playerId; state.message = rank === '10' ? '10 burned the pile — play again.' : 'Four of a kind — pile cleared!'; } else { state.activePlayer = other(state, playerId).id; const active = getActivePileState(state.discard); state.message = rank === '2' ? 'Pile reset.' : rank === '3' ? `3 is transparent${active.effectiveRank ? ` — ${active.effectiveRank} remains active.` : '.'}` : rank === 'A' ? 'Special card required.' : 'Card played.'; } checkWinner(state, player); state.version++; return state; }
export function resolveFaceDownAttempt(current, playerId, cardId, expectedVersion) { if (current.version !== expectedVersion) throw new Error('STALE_ACTION'); if (current.activePlayer !== playerId) throw new Error('NOT_YOUR_TURN'); const state = clone(current); const player = playerFor(state, playerId); if (state.drawPile.length || player.hand.length || player.faceUp.length) throw new Error('FACE_DOWN_NOT_AVAILABLE'); const card = player.faceDown.find((c) => c.id === cardId); if (!card) throw new Error('CARD_UNAVAILABLE'); player.faceDown = player.faceDown.filter((c) => c.id !== cardId); if (!canPlayCards(state.discard, [card])) { player.hand.push(...state.discard, card); state.discard = []; state.activePlayer = playerId; state.version++; state.message = 'Face-down card could not be played — pick up the pile.'; return state; } player.hand.push(card); return resolvePlay(state, playerId, [card.id], expectedVersion); }
export function pickupPile(current, playerId, expectedVersion) { if (current.version !== expectedVersion) throw new Error('STALE_ACTION'); if (current.activePlayer !== playerId) throw new Error('NOT_YOUR_TURN'); const state = clone(current); if (!state.discard.length) throw new Error('EMPTY_PILE'); const player = playerFor(state, playerId); player.hand.push(...state.discard); state.discard = []; state.activePlayer = playerId; state.version++; state.message = 'Pile picked up — start a new sequence.'; return state; }
export function projectForPlayer(state, playerId) { const player = playerFor(state, playerId); if (!player) throw new Error('NOT_A_PLAYER'); const opponent = other(state, playerId); return { id: state.id, version: state.version, activePlayer: state.activePlayer, winner: state.winner, message: state.message, drawCount: state.drawPile.length, discard: state.discard, player, opponent: { id: opponent.id, handCount: opponent.hand.length, faceUp: opponent.faceUp, faceDownCount: opponent.faceDown.length } }; }
